### ISSUE TITLE
打不开工程

### ISSUE THREAD

**Issue by guo787269125** [VegetableWithChicken/OpenCV_DNN_FaceRecognize_For_UnrealEngine#2]
在工程中添加了插件，也进行了重新编译且成功了，发现就打不开工程了，删掉插件就可以打开。重新添加插件到Plugins目录就打不开工程，也没有报错，也没有打开工程。
使用的是UE5.0.3

**Comment by VegetableWithChicken** [comment]
是不是缺少dll文件，
- 我的工程编译环境是4.27
- 麻烦log上传一下

**Comment by VegetableWithChicken** [comment]
now has supported unreal 5.0
