### ISSUE TITLE
可不可以分享个使用该插件的demo UE5工程项目？

### ISSUE THREAD

**Issue by skyz8421** [VegetableWithChicken/OpenCV_DNN_FaceRecognize_For_UnrealEngine#7]
非常好的插件！但作为UE5小白，作者能不能再分享一个使用该插件的完整UE5 demo项目，作为个人学习？非常感谢作者的工作

**Comment by VegetableWithChicken** [comment]
好的，这可能需要一点时间，我会抽空发布的，请关注这个仓库更新情况
https://github.com/VegetableWithChicken/OpenCVForUnrealSample
