### ISSUE TITLE
Hi there! UE5.2

### ISSUE THREAD

**Issue by ArtemkaSvyat** [VegetableWithChicken/OpenCV_DNN_FaceRecognize_For_UnrealEngine#8]
Hi!! Thanks for amazing plugin! Using it now with ue4.27! Wonder if you can upgrade it to ue5.2 version? tryes by myself but had such errors with ints

E:\Tests\wwe\HostProject\Plugins\HiKVision\Source\HiKVision\Public\HiKVisionActor.h(84): error C2665: "UE::Math::TVector2<double>::TVector2": ни одна перегруженная функция не может преобразовать все типы аргументов
E:\UE_5.2\Engine\Source\Runtime\Core\Public\Math\Vector2D.h(707): note: может быть "UE::Math::TVector2<double>::TVector2(UE::Math::TVector2<double> &&)"
E:\Tests\wwe\HostProject\Plugins\HiKVision\Source\HiKVision\Public\HiKVisionActor.h(84): note: "UE::Math::TVector2<double>::TVector2(UE::Math::TVector2<double> &&)": невозможно преобразовать аргумент 1 из "int" в "UE::Math::TVector2<double> &&"
E:\Tests\wwe\HostProject\Plugins\HiKVision\Source\HiKVision\Public\HiKVisionActor.h(84): note: Причина: невозможно преобразовать "int" в "UE::Math::TVector2<double>"
E:\Tests\wwe\HostProject\Plugins\HiKVision\Source\HiKVision\Public\HiKVisionActor.h(84): note: Конструктор для struct "UE::Math::TVector2<double>" объявлен как "explicit"
E:\UE_5.2\Engine\Source\Runtime\Core\Public\Math\Vector2D.h(707): note: или       "UE::Math::TVector2<double>::TVector2(const UE::Math::TVector2<double> &)"
E:\Tests\wwe\HostProject\Plugins\HiKVision\Source\HiKVision\Public\HiKVisionActor.h(84): note: "UE::Math::TVector2<double>::TVector2(const UE::Math::TVector2<double> &)": невозможно преобразовать аргумент 1 из "int" в "const UE::Math::TVector2<double> &"
E:\Tests\wwe\HostProject\Plugins\HiKVision\Source\HiKVision\Public\HiKVisionActor.h(84): note: Причина: невозможно преобразовать "int" в "const UE::Math::TVector2<double>"
E:\Tests\wwe\HostProject\Plugins\HiKVision\Source\HiKVision\Public\HiKVisionActor.h(84): note: Конструктор для struct "UE::Math::TVector2<double>" объявлен как "explicit"
E:\UE_5.2\Engine\Source\Runtime\Core\Public\Math\Vector2D.h(86): note: или       "UE::Math::TVector2<double>::TVector2(T,T)"
        with
        [
            T=double
        ]
E:\Tests\wwe\HostProject\Plugins\HiKVision\Source\HiKVision\Public\HiKVisionActor.h(84): note: UE::Math::TVector2<double>::TVector2: функция не принимает 1 аргументов
E:\UE_5.2\Engine\Source\Runtime\Core\Public\Math\Vector2D.h(78): note: или       "UE::Math::TVector2<double>::TVector2(void)"
E:\Tests\wwe\HostProject\Plugins\HiKVision\Source\HiKVision\Public\HiKVisionActor.h(84): note: UE::Math::TVector2<double>::TVector2: функция не принимает 1 аргументов
E:\UE_5.2\Engine\Source\Runtime\Core\Public\Math\Vector2D.h(101): note: или       "UE::Math::TVector2<double>::TVector2(UE::Math::TIntPoint<OtherIntType>)"
E:\Tests\wwe\HostProject\Plugins\HiKVision\Source\HiKVision\Public\HiKVisionActor.h(84): note: 'UE::Math::TVector2<double>::TVector2(UE::Math::TIntPoint<OtherIntType>)': не удалось вывести аргумент шаблон для 'UE::Math::TIntPoint<OtherIntType>' из 'int'
E:\Tests\wwe\HostProject\Plugins\HiKVision\Source\HiKVision\Public\HiKVisionActor.h(84): note: при попытке сопоставить список аргументов "(int)"

maybe you have any ideas how to fix that? Appreciate any help)

**Comment by VegetableWithChicken** [comment]
It has been fixed and version 5.2 has been released, thanks for the suggestion
